apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: order-service-rolebinding
  namespace: ecommerce

subjects:
  - kind: ServiceAccount
    name: order-service-sa
    namespace: ecommerce

roleRef:
  kind: Role
  name: order-service-role
  apiGroup: rbac.authorization.k8s.io