apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-service-deployment
  namespace: ecommerce

spec:
  replicas: 1

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      containers:
        - name: product-service
          image: product-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 12



          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: DB_URL

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: product-service-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-service-secret
                  key: DB_PASSWORD

            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: SPRING_PROFILES_ACTIVE


            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: SERVER_PORT
