spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: product-service

              uri: http://product-service:8080

              predicates:
                - Path=/api/v1/products/**

            - id: order-service
              uri: http://order-service:8080
              predicates:
                - Path=/api/v1/orders/**

            - id: payment-service
              uri: http://payment-service:8080
              predicates:
                - Path=/api/v1/payments/**

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      probes:
        enabled: true