apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway-deployment
  namespace: ecommerce

spec:
  replicas: 1

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: api-gateway

  template:

    metadata:
      labels:
        app: api-gateway

    spec:

      containers:

        - name: api-gateway

          image: api-gateway:2.0
          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 12

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          env:

            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: SPRING_PROFILES_ACTIVE

            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: SERVER_PORT